# Generated by Django 3.2.3 on 2021-12-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_name',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
    ]
